site_name: Wangzh

# Copyright
copyright: 'Copyright &copy; 2020-2024 Wangzh'



theme:
  name: material
  logo: assets/avatar.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
  - navigation.top
  - navigation.tabs
  - content.code.copy # 代码块复制按键
  - search.suggest # 搜索建议
  - search.highlight # 搜索结果高亮/突出显示
  - search.share # 搜索结果分享

  
markdown_extensions:
  - toc:
      permalink: "¶"
  - pymdownx.superfences
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.arithmatex: # f 显示 LaTeX 数学公式
  - pymdownx.tasklist: # a
      custom_checkbox: true
  - pymdownx.critic # b Formatting 含 高亮/删除线/下划线/上下角标 [等]
  - pymdownx.caret # b
  - pymdownx.keys # b
  - pymdownx.mark # b
  - pymdownx.tilde # b
  - footnotes # 脚注
  - pymdownx.tabbed: # e
      alternate_style: true 
  - md_in_html # 在 md 文档中能显示 html 的效果

      
extra_css:
  - stylesheets/special.css
plugins:
  - blog:
  - search
  - tags
  - git-revision-date-localized: # 页面下方创建和修改时间
      enable_creation_date: true
      type: timeago

  - statistics: # 统计页面字数、代码行数、阅读时间
      page_read_time: true
      page_check_metadata: comments
# extra:
#   homepage: index.html  # 指定你的自定义HTML文件名